#!/bin/env php
<?php

require 'autoload.php';

$from = new Pff\TaskSync\Provider\Asana('api_key');
$to = new Pff\TaskSync\Provider\Toggl('api_key');

$differ = new Pff\TaskSync\Differ();

$processor = new Pff\TaskSync\Processor($from, $to, $differ);

var_export($_SERVER['argc']);

$processor->listWorkspaces();

// $diff = $processor->diffWorkspace('from_workspace_id', 'to_workspace_id');
// $processor->saveDiff('to_workspace_id', $diff);
